"""Build the readable browser data module from approved educational sources.

Run build_evidence.py and verify_evidence.py first when changing evidence.
This packaging step does not interpolate, normalize, or reinterpret any data.
The browser has no build/runtime dependency on Python or these source files.
"""
from pathlib import Path
import argparse
import json


ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT.parents[2] / 'vilda_hormone_lifespan_data.js'


def build():
    male = (ROOT / 'schematic-data.js').read_text(encoding='utf-8').strip()
    reference = json.loads((ROOT / 'female-reference-data.json').read_text(encoding='utf-8'))
    lifespan = json.loads((ROOT / 'female-lifespan-data.json').read_text(encoding='utf-8'))
    patient_points = json.loads((ROOT / 'population-reference-data.json').read_text(encoding='utf-8'))
    reference_js = json.dumps(reference, ensure_ascii=False, indent=2)
    lifespan_js = json.dumps(lifespan, ensure_ascii=False, indent=2)
    patient_points_js = json.dumps(patient_points, ensure_ascii=False, indent=2)
    return (
        '/* Educational hormone lifespan data; not reference intervals or patient scoring.\n'
        ' * Generated by docs/clinical/hormone-lifespan/build_runtime.py.\n'
        ' * Sources, limitations and approved presentation: docs/clinical/HORMONE_LIFESPAN.md.\n'
        ' * Edit the readable sources and regenerate; do not edit this artifact separately.\n'
        ' */\n'
        '(function (root, factory) {\n'
        "  'use strict';\n"
        '  var data = factory();\n'
        "  if (typeof module === 'object' && module.exports) module.exports = data;\n"
        '  if (root) root.VildaHormoneLifespanData = data;\n'
        "})(typeof window !== 'undefined' ? window : null, function () {\n"
        f'{male}\n'
        f'const referenceData = {reference_js};\n'
        f'const lifespanData = {lifespan_js};\n'
        f'const patientPointData = {patient_points_js};\n'
        'return {\n'
        '  version: lifespanData.version,\n'
        '  maleAges: maleAges,\n'
        '  maleHormones: maleHormones,\n'
        '  maleStages: maleStages,\n'
        '  referenceData: referenceData,\n'
        '  lifespanData: lifespanData,\n'
        '  patientPointData: patientPointData\n'
        '};\n'
        '});\n'
    )


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if the checked-in browser artifact is stale')
    args = parser.parse_args()
    content = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != content:
            raise SystemExit('FAIL: vilda_hormone_lifespan_data.js differs from its sources; run build_runtime.py')
        print('PASS: browser data exactly reproduce the approved sources')
    else:
        OUTPUT.write_text(content, encoding='utf-8')
        print(OUTPUT.name)
