version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:10"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      development-minor-patch:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(actions)"
